"""Add image column to FoodItem model

Revision ID: fe8c9a03f5e2
Revises: f8b95136172a
Create Date: 2024-07-31 13:58:06.293672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8c9a03f5e2'
down_revision = 'f8b95136172a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
